### ISSUE TITLE
Documented API for Google Health Data

### ISSUE THREAD

**Issue by fccoelho** [thegraphnetwork/epigraphhub_py#106]
## 🚀 Feature Request

We need a documented API to pull data from [Google COVID19 repository](https://health.google.com/covid-19/open-data/raw-data)

**Comment by eduardocorrearaujo** [comment]
I was looking at the google cloud data and they just provide a link that you can use to access the data like the foph datasets. 

For this reason, I was thinking about just writing a script to put this data on the platform as we did with the foph data, and writing some examples explaining how this data can be used. I think that would be better to put this data in our database to aggregate value to it. 

If you agree with this idea I would like to know if these scripts should be put in this repo, or in the epigraphhub repo with the `foph.py` and `colombia.py` files.

**Comment by eduardocorrearaujo** [comment]
I found the link to access the data in this link: https://github.com/GoogleCloudPlatform/covid-19-open-data. 

I compile the links associated with the respective tables in this dictionary: 

```
dict_tables = {
    'index':'https://storage.googleapis.com/covid19-open-data/v3/index.csv', 
    'demographics': 'https://storage.googleapis.com/covid19-open-data/v3/demographics.csv', 
    'economy': 'https://storage.googleapis.com/covid19-open-data/v3/economy.csv', 
    'epidemiology': 'https://storage.googleapis.com/covid19-open-data/v3/epidemiology.csv', 
    'emergency_declarations': 'https://storage.googleapis.com/covid19-open-data/v3/lawatlas-emergency-declarations.csv',
    'geography': 'https://storage.googleapis.com/covid19-open-data/v3/geography.csv',
    'health': 'https://storage.googleapis.com/covid19-open-data/v3/health.csv', 
    'hospitalizations': 'https://storage.googleapis.com/covid19-open-data/v3/hospitalizations.csv', 
    'mobility': 'https://storage.googleapis.com/covid19-open-data/v3/mobility.csv', 
    'search_trends': 'https://storage.googleapis.com/covid19-open-data/v3/google-search-trends.csv', 
    'vaccnation_access': 'https://storage.googleapis.com/covid19-open-data/covid19-vaccination-access/facility-boundary-us-all.csv',
    'vaccination_search': 'https://storage.googleapis.com/covid19-open-data/covid19-vaccination-search-insights/Global_vaccination_search_insights.csv',
    'vaccinations': 'https://storage.googleapis.com/covid19-open-data/v3/vaccinations.csv',
    'government_response': 'https://storage.googleapis.com/covid19-open-data/v3/oxford-government-response.csv', 
    'weather': 'https://storage.googleapis.com/covid19-open-data/v3/weather.csv', 
    'worldbank': 'https://storage.googleapis.com/covid19-open-data/v3/worldbank.csv', 
    'epid_hosp_by_age': 'https://storage.googleapis.com/covid19-open-data/v3/by-age.csv', 
    'epid_hosp_by_sex': 'https://storage.googleapis.com/covid19-open-data/v3/by-sex.csv'
    }
```
I just think that we don't need to put the `worldbank`data since we have another code to directly access this data.

**Comment by fccoelho** [comment]
Please go ahead @eduardocorrearaujo!  Regarding the Worldbank table, we may stil download it since it maybe a transformation ofa dataset from the Worldbank, not necessarily something that we can fetch from there.

Please don't forget to add indices to the tables, particularly in dates columns and locality names, it can greatly speed up visualizations.

**Comment by eduardocorrearaujo** [comment]
Ok, this code must be saved in this repo or in the Epigraphhub repo with the `foph.py` and `colombia.py`?

**Comment by fccoelho** [comment]
Yes, you can create a Google Health schema to hold it.
