### ISSUE TITLE
Module to make plots 

### ISSUE THREAD

**Issue by eduardocorrearaujo** [thegraphnetwork/epigraphhub_py#130]
## 🚀 Feature Request
Module to make plots 

I think that would be interesting to have a module with functions to make specific plots useful for analyzing health data. If you have some idea of ​​plots, put them here and with time I will work to create the functions to create these plots.

**Comment by dcpcamara** [comment]
I'm gonna do some bomb dropping / brainstorm on ideas in here. In our 2020 project and for WHO we've made some graphs, maps and tables that can be used for basically any epi situation.

Weekly and/or daily table with some useful epi indicators and descriptive statistics. This can/should be updated depending on the disease we are studying. The following example is for COVID-19:
![image](https://user-images.githubusercontent.com/22399860/154489768-f4e974f7-f5c8-4b2a-8b4f-60892e0b106d.png)

Daily and/or weekly epicurve. It seems that general opinion after the COVID-19 pandemic likes this timeseries barplot with a smoothing curve (7-day moving average in the example). This could be done for any important indicator (such as cases, incidence, deaths, mortality, # of tests, # of vaccinated per dose, etc). 
![image](https://user-images.githubusercontent.com/22399860/154490052-09c19704-5b46-469d-bb1a-a033cb2c3a9c.png)
![image](https://user-images.githubusercontent.com/22399860/154490118-6c4efb07-029d-486e-b120-a0cad8f6569b.png)

I kind of like the idea of having a growth-rate graph that can easily indicate the trend of the transmission. We could be making such plots for Rt also, for instance.
![image](https://user-images.githubusercontent.com/22399860/154490729-c4166a9e-c261-4fd6-a6df-51dc9a78c9ae.png)

Some mapping could be done for any administrative level. This one is for the whole Africa, but regional mapping can be of great use. I don't know why my work with regional maps was not integrated into this dashboard, but nonetheless, it is something that can be easily done.
![image](https://user-images.githubusercontent.com/22399860/154490818-5d3726dd-a1dc-4eb8-aa6f-b9148dbf11be.png)

Other graphs that I'm fond of are decomposing timeseries into trend and sazonality (which could be done via curves) and timeseries boxplots - although the general public usually is not very familiar with boxplots. 

The above examples are pratically constructed with one or two dimensions at most. Some useful plotting that we can explore can involve three variables, which can be easily done in dispersion plots and maps. I have all these examples in R code if you want to take a look, both in static perspective (e.g., ggplot2) or dynamic/interactive (e.g., plotly). They can be found in the push that Lucas did with some material of the dashboard that we've implement for WHO Afro.

Whew... sorry for the long message.

**Comment by eduardocorrearaujo** [comment]
Thank you for the answer. I will take a look in this codes. By the way, I think that this code that you and Lucas have can be used to start the  epigraphhub R package.

**Comment by dcpcamara** [comment]
Definitely! However, to my understand the R package would first focus on a translation of the Python package or am I wrong?

**Comment by xmnlab** [comment]
I thought we will move all R code to a new repo ... that is why it would be good to have it early than later.
but maybe I am wrong.

**Comment by dcpcamara** [comment]
lol maybe we could have a chat with @fccoelho to understand the process better?

**Comment by fccoelho** [comment]
We can discuss this at our first meeting. But the Idea is that most features should be available on both Languages, therefore it may even mak sense to maintain an integrated documentation with code examples in both languages side-by-side, what do you think?

**Comment by fccoelho** [comment]
I liked your visualization suggestions @dcpcamara! Perhaps we can do some kind of Documentation-driven development! :-)

**Comment by xmnlab** [comment]
that sounds great.

**Comment by eduardocorrearaujo** [comment]
Ok!

**Comment by fccoelho** [comment]
I would suggest we work to compensate the weak spots of Superset, namely the visualization of Geo-Reference datasets. 
We can also think about creating a showcase Streamlit dashboard to demo this visualization module.
Welcome @NicoRicardi  to our team! feel free to add your own views about this here in this thread.
