### ISSUE TITLE
Worldpop data

### ISSUE THREAD

**Issue by fccoelho** [thegraphnetwork/epigraphhub_py#157]
## 🚀 Feature Request

Add support for downloading data from [WorldPop](https://www.worldpop.org)

They have a Python client library for this: https://github.com/wpgp/wpgpDownloadPy

Our PostGIS database can store the rasters directly. If you are not very familiar with raster data this is a good resource:
https://carpentries-incubator.github.io/geospatial-python/aio/index.html

**Comment by dcpcamara** [comment]
@fccoelho are we going to do this in R too?

**Comment by fccoelho** [comment]
> @fccoelho are we going to do this in R too?

Why not? I think they offer an R library as well
