### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by fccoelho** [thegraphnetwork/epigraphhub_py#164]
The README now is basically the one that came with the cookiecutter template.

Rewrite the README keeping useful aspects of the current one but including upfront a description of the package, examples, link to the documentation, etc.

**Comment by fccoelho** [comment]
Link to the documentation: https://readthedocs.org/projects/epigraphhub-libraries/

**Comment by fccoelho** [comment]
@xmnlab maybe Yurely or Anavelyz could tackle this issue as well?

**Comment by xmnlab** [comment]
Sure thing!

@yurelycamacho @anavelyz could you work on this? I think it would be a good first task about the documentation :)

**Comment by fccoelho** [comment]
Great! I have invited @YurelyCamacho and @Anavelyz to the documentation team!

**Comment by eduardocorrearaujo** [comment]
@Anavelyz  I think in the readme, we could have a section explaining how to contribute to the project. In this section, we could have something following the instructions that @xmnlab  sent me some time ago: 
```
btw, the common workflow for an opensource project using git/github are:

- fork the official project to your own github account
- clone your own fork, eg: git clone
- add a upstream remote repository, ex: git remote add upstream
- update your local git indexes: git fetch --all

for each new branch you want to create:

- point to upstream/main: git checkout upstream/main
- create a new branch: git checkout -b mynewbranch
add any new code to upstream/main via PR
```

**Comment by xmnlab** [comment]
@eduardocorrearaujo 
maybe in the readme we could have just a link to CONTRIBUTING.md and we could keep all this information there. for example:

```md
## How to contribute

If you want to contribute to EpiGraphHubPy, check our [Contributing Guide](./CONTRIBUTING.md).

```
