### ISSUE TITLE
Refactor the package

### ISSUE THREAD

**Issue by eduardocorrearaujo** [thegraphnetwork/epigraphhub_py#168]
By now, the epigraphhub is organized as follows:
** - represents a file inside a subfolder
Epigraphhub/

- analysis/:
      - clustering.py
      - epistats.py
      - restim.py
      
- data/
      - epigraphhub.py
      - foph.py
      - ggtrends.py
      - preprocessing.py
      - upload.py
      - worldbank.py
      - worldpop.py
    
- models /
      - lstm_models.py
      - ngboost_models.py
      - plots.py
      - sklearn_models.py

And the examples folder is organized as follows:

Examples/
    - trends.ipynb;
    - worlbank.ipynb;
    - worldpop.ipynb.
    - forecast_switzerland/

I propose the change:

Epigraphhub/

-   analysis/
          - temporal/
                ** clustering.py
          - epistats.py
          - restim.py

-   data/
         - epigraphhub.py
         - covid/
                 ** foph.py
          - ggtrends.py
          - **preprocessing.py** (move to models folder)
          - **upload.py** (rename to upload_geofile.py)
        - indicators/
                      ** worldbank.py
                      ** worldpop.py
                      
-   **forecast_models** (rename models) /
        - preprocessing.py
        - ml/
              ** sklearn_models.py
              ** ngboost_models.py
              ** plots.py (maybe we could rename to make_plots.py
        - nn (neural network)/
              ** lstm_models.py

And the examples folder it will be organized as follows:

The idea is the notebooks has the same name of the .py files and following the same structure shown above:

Examples/
- analysis
- data
- models
- forecast_switzerland/

**Comment by xmnlab** [comment]
I think maybe it would be better if we rename the `Examples` folder to `tutorial`, and move it to inside the `docs` folder.
Also, I recommend to standardize the name of the folders to use always lower case.

**Comment by eduardocorrearaujo** [comment]
I agree, thank you for your contribution, @xmnlab.

**Comment by fccoelho** [comment]
Some initial suggestions:

- Move all plot related code in to a subpackage named `plotting`or something similar.
- in the data packages create subpackages by sources and inside we can have modules by dataset from that source.
- `models` should be a subpackage of analysis. Inside we can have modules or subpackages for types of models.

**Comment by eduardocorrearaujo** [comment]
> Some initial suggestions:
> 
> * Move all plot related code in to a subpackage named `plotting`or something similar.
> * in the data packages create subpackages by sources and inside we can have modules by dataset from that source.
> * `models` should be a subpackage of analysis. Inside we can have modules or subpackages for types of models.

I was thinking about keeping the forecast models in a separate folder. Otherwise, I think that the path to the models will be too long: 
"from epigraphhub.analysis.models.forecast.ngboost_models import xxxxxxx"
It's just an opinion looking at the scipy docs.

Other point that I saw in scipy, is keep the tests in the folder with the code instead of the main folder. What do you think about it?
