### ISSUE TITLE
Generalize functions in epistats.py

### ISSUE THREAD

**Issue by eduardocorrearaujo** [thegraphnetwork/epigraphhub_py#173]
## 🚀 Feature Request

It's necessary to generalize the functions in epigraphhub/analysis/epistats.py. 

@fccoelho Do you have any recommendations?

**Comment by fccoelho** [comment]
The functions in this module are already applicable to any disease, so no generalization is needed

**Comment by fccoelho** [comment]
the module has been improved in PR #172

**Comment by fccoelho** [comment]
closing this one.
