### ISSUE TITLE
Removing documentation  folder

### ISSUE THREAD

**Issue by fccoelho** [thegraphnetwork/epigraphhub_py#175]
Since we are maintaining the documentation on a [separate repo](https://github.com/thegraphnetwork/epigraphhub-lib-docs), we should delete the docs folder to avoid confusion.

**Comment by xmnlab** [comment]
should the tutorial folder there be moved to https://github.com/thegraphnetwork/epigraphhub-lib-docs ?

**Comment by fccoelho** [comment]
I think that to be consistent with our organization of the documentation, it should be moved as well.
