### ISSUE TITLE
Installation issue: numpy 

### ISSUE THREAD

**Issue by NicoRicardi** [thegraphnetwork/epigraphhub_py#177]
## 🐛 Bug Report

Installation with Python3.10 lead to a "cannot build wheel for numpy" error

## 🔬 How To Reproduce

1. Install with pip in a Python3.10 environment

### Environment

* OS: Linux (xubuntu)
* Python version, get it with: Python3.10

```bash
python --version
```

**Comment by fccoelho** [comment]
Closing this as not an issue of this library. BTW, technical issues not associated with software developed by us should be posted as questions on discord.
