### ISSUE TITLE
Installation issue: poetry did not work

### ISSUE THREAD

**Issue by NicoRicardi** [thegraphnetwork/epigraphhub_py#178]
## 🐛 Bug Report

Initially I got an error claiming my Python version was the issue. The requirement was Python =>3.9, <4, which Python3.10 actually meets.
Now I get a different error (epigraphhub is listed as a dependency of itself).

## 🔬 How To Reproduce

Not really sure.

### Environment

* OS: Linux
* Python version, get it with: Python3.10

```bash
python --version
```

**Comment by fccoelho** [comment]
Maybe ths has been solved since the last release of epigraphhub?

**Comment by fccoelho** [comment]
Closing. @NicoRicardi, please re-open it still an active issue
