### ISSUE TITLE
Create separate directories for each disease in sinan_fetch script

### ISSUE THREAD

**Issue by esloch** [thegraphnetwork/epigraphhub_py#189]
## 🚀 Feature Request

Improve the structure of files downloaded by disease for reading DAGs in airflow.

**Comment by luabida** [comment]
Notes:
The way it is right now, the Airflow will try to fetch the 150+ parquet files to database at the same time, causing too much memory overhead.

Possible solution:
Pre-fetch the years for each disease, where Tasks won't differentiate by year, only by disease.
Example: download('zika')

This way Airflow will handle better the asynchronicity (even if takes more time to finish a disease).

**Comment by luabida** [comment]
I think it is good to have a method to remove the parquet files, separated from the other methods so Airflow can call.

**Comment by fccoelho** [comment]
@luabida you mean having one task per disease having them iterate over the multiple years? If so, I agree.

**Comment by luabida** [comment]
Yes, I was able to do this way, but during the tests, a single decode error on PySUS is capable of ruining the process. I will need to modify the SINAN script to make this work.

**Comment by fccoelho** [comment]
That is an issue that needs 

> NOTE: 141 decode errors during the download test, maybe we will have to do it differently

This is an Issue that should be fixed and tested in PySUS. Please Open an issue there, @luabida .

**Comment by luabida** [comment]
funny enough, I've found a package for reading DBC files inspired on PySUS 😂
https://github.com/gbletsch/pydbc

Trying to see if this package can help us out here

**Comment by xmnlab** [comment]
Interesting :) is it better than pyreaddbc?

**Comment by luabida** [comment]
> is it better than pyreaddbc?

I wasn't aware of this package, thanks for sharing. About pydbc, I couldn't make it work, maybe some C dependencies that I've no experience with.

**Comment by luabida** [comment]
Converting DBC files to DBF is very quick, but converting DBC or DBF files to dataframe consumes tons of memory (at least on my machine). Do you know if there is a way of getting rid of this middle process, send the DBF file directly into the SQL server and get the dataframes via SQL queries?
