### ISSUE TITLE
Unity Tests: Coverage and enhancement

### ISSUE THREAD

**Issue by luabida** [thegraphnetwork/epigraphhub_py#204]
## ⚙️ Refactor Request

This issue aims to scrape the epigraphhub library, searching for untested methods, including them into unitary tests.
Also refactor the tests structure to embrace issue #202 

## 🔈 Motivation

Following best practices, every end-point method should be included in the unitary test coverage.
It is also a good idea to have a well defined unity tests structure, so it could be easily reproducible for new functionalities.

## 🛰 Alternatives

I don't have any coverage framework in mind, if someone knows a good one, please link it in this issue.

**Comment by luabida** [comment]
@xmnlab I have a question about this subject. When we talk about methods that use the database to insert or request data, what should be the best practice in this case? Should the tests be able to interact with the sql server?

**Comment by xmnlab** [comment]
Normally we have a database on CI for that purpose

**Comment by luabida** [comment]
You mean a postgres on docker to be built with all the structure, ready to use in the tests?

**Comment by xmnlab** [comment]
Yep ... normally we don't need to test with all data. Sometimes just a synthetic data or some few rows are enough for the tests
