### ISSUE TITLE
Add functions to get the data from the database

### ISSUE THREAD

**Issue by eduardocorrearaujo** [thegraphnetwork/epigraphhub_py#61]
The functions will be used initially to get the data from Switzerland, but the idea is to generalize them to other countries.

**Comment by fccoelho** [comment]
@eduardocorrearaujo is this issue still active? if not see if  it should be updated or closed.

**Comment by eduardocorrearaujo** [comment]
By now, the general functions (that can work with almost any dataset) to get data from the database are described in this example: https://github.com/thegraphnetwork/epigraphhub_py/blob/main/docs/tutorials/data/epigraphhub_db.ipynb

@fccoelho If you have any idea of other functions that could be developed, describe the function here, and I will work on the implementation.
