### ISSUE TITLE
CI: release-drafter.yml triggered on `master`

### ISSUE THREAD

**Issue by xmnlab** [thegraphnetwork/epigraphhub_py#72]
The github actions workflow https://github.com/thegraphnetwork/epigraphhub_py/blob/main/.github/workflows/release-drafter.yml
is triggered by `push` event on `master` branch.

is it still useful? if so, it should be updated to listening to `main` branch instead.

cc @fccoelho

**Comment by fccoelho** [comment]
Agreed! I'll change that.
